name: flutter_app_rename
description: A package that makes it easy to set your flutter app launcher name. 
version: 0.1.2+packagename
maintainer: fiskindal
homepage: https://github.com/fiskindal/flutter_app_rename

dependencies:
  yaml: ^3.1.0
  xml: ^6.3.0
  rename: ^2.1.1

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  test: ^1.16.6

flutter_app_name:
  name: "Flutter App Name"
